roles/demo_certs/tasks/main.yml, roles/redpanda_broker/defaults/main.yml, roles/redpanda_broker/tasks/install-certs.yml, roles/redpanda_broker/tasks/main.yml
Install certs fit awkwardly into the demo certs role because you need to be able to install certs when running TLS. This commit moves them into the main role.
This change will also ensure that the end user is able to set custom certs in the playbook, giving them greater flexibility.
=> move install_certs into main role

roles/redpanda_broker/defaults/main.yml, roles/redpanda_broker/tasks/main.yml
Users should provide a specific version, although if they choose to use latest that's fine too.
=> fail if no version is provided

roles/redpanda_broker/defaults/main.yml, roles/redpanda_broker/tasks/data-dir-perms.yml, roles/redpanda_broker/tasks/install-node-deps.yml, roles/redpanda_broker/tasks/install-redpanda.yml, roles/redpanda_broker/tasks/main.yml, roles/redpanda_broker/tasks/prepare-data-dir.yml, roles/redpanda_broker/tasks/start-redpanda.yml, roles/redpanda_broker/templates/configs/defaults.j2, roles/redpanda_broker/templates/configs/tiered_storage.j2, roles/redpanda_broker/templates/configs/tls.j2
This PR makes the necessary changes to remove the install script from the repo in support of the air gap project while replacing ever more static strings with variables users can set to improve their ability to control the install process. In addition I've swapped us from YAML to JSON for the templates so that we're better able to modularly include/exclude elements without running into mapping issues.
- Bash Install Script Removal for RPM/DEB (Ansible changes)
=> remove install script and use json

roles/redpanda_broker/defaults/main.yml
This fix ensures we set el rather than redhat for rhel systems.
=> fix for repo config on rhel

galaxy.yml, roles/demo_certs/tasks/issue-certs.yml
This task often fails due to a race condition with "Unable to rename /workdir/ansible/tls/ca/serial.txt.new to /workdir/ansible/tls/ca/serial.txt". While we could fix this task by setting serial to 1, this would render the playbook unusable as the number of brokers increases. Also, it usually doesn't hit the race condition. As an alternative solution to a really annoying but ultimately harmless bug I've added a retry with a small delay for errors.
=> Add retry to issue certs

roles/redpanda_broker/tasks/configure-deb-repository.yml, roles/redpanda_broker/tasks/configure-rpm-repository.yml
When install_console is true we default to standard rather than unstable as no unstable version is published to our apt/dnf repositories.
=> fixes the lack of an unstable version for console

galaxy.yml, roles/redpanda_broker/defaults/main.yml, roles/redpanda_broker/templates/configs/defaults.j2, roles/redpanda_broker/templates/configs/tls.j2
This PR introduces the schema registry configuration for the redpanda.yaml and enables schema registry on start. It supports TLS configurations too.
=> Broker: enable schema registry 

roles/redpanda_broker/tasks/install-rp-deb.yml, roles/system_setup/tasks/install-node-deps-deb.yml, roles/system_setup/tasks/install-node-deps-rpm.yml
Basically, google has some internal access points for various public registries that are messed up by using apt/dnf proxying. I've added some workarounds to eliminate the issue. There's no reason to override Google's functionality since it's strictly superior to using Squid.
=> Changes for GCP Proxy

roles/redpanda_broker/templates/configs/tiered_storage.j2
Had been enabling this thru the redpanda variable during testing but forgot to include it in the PR for whatever reason.
=> Add GCP Storage API to enable tiered storage

galaxy.yml, roles/redpanda_broker/templates/console/defaults.j2
This PR adds the [Schema Registry](https://docs.redpanda.com/current/manage/console/schema-registry/) section to the redpanda-console configuration YAML. 
Now a user does not have to update the configuration to enable schema registry:
=> console: add schema registry configuration

galaxy.yml, roles/redpanda_broker/defaults/main.yml, roles/redpanda_broker/templates/console/defaults.j2
This PR introduces a new set of variables to the Ansible collection:
- console_certs_dir
- console_key_file
- console_cert_file
Those are the paths either to the dir or to the key and cert file for the console front end.
The user can either use our certs creation (not recommended) or provide their own certs in the cluster and client (as [shown here](https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/manual/production/production-deployment-automation/#build-the-cluster-with-tls-enabled) in the docs)
```
ansible-playbook ansible/provision-tls-cluster.yml \
--private-key '<path-to-a-private-key-with-ssh-access-to-the-hosts>' \
--extra-vars create_demo_certs=false \
--extra-vars advertise_public_ips=false \
--extra-vars handle_certs=false \
--extra-vars …
```
=> Add TLS to Console Front End.

galaxy.yml, roles/redpanda_broker/templates/configs/defaults.j2
Empty rack id could still cause rack: config to show up in json data structure. this ends up allowing an empty rack name to show up in the redpanda.yaml, causing follower fetching to enable even if rack awareness is turned off explicitly. This appears to cause some strange behavior with _schema topic and Schema Registry, making it throw 50002 errors.
=> Fix handling of empty rack id.

roles/redpanda_broker/tasks/start-redpanda.yml
Initially I fixed a templating error that was causing crashes in newer versions of ansible due to deprecation of the old method. This change revealed that the current method of change detection doesn't work. As a result I've removed it as I didn't see much point keeping useless code. 
I also added a comment explaining why I'm not checking for change anymore.
=> fix: jinja2 templating error

galaxy.yml, roles/sysctl_setup/defaults/main.yml
to better accommodate larger Redpanda setups. This appears to fix issues with inconsistent connectivity to Schema Registry.
=> Bump inotify max_user_instances default

galaxy.yml, roles/redpanda_broker/templates/configs/defaults.j2
panda proxy API was started with '[' instead of '{'.
=> [bug]: fix jinja template error

roles/redpanda_broker/tasks/install-rp-deb.yml, roles/redpanda_broker/tasks/install-rp-rpm.yml
In testing #100 is appears that `register` still registers a result even if the `when` clause evaluates to `false`.
Explaining this change:
We currently have three `package` commands which do the same thing except controlled by the setting of three variables:
`Install redpanda from repository (Proxy)` is executed when:
```
- https_proxy_value is defined
- https_proxy_value | length > 0
- (using_gcp | default(false)) is false
```
`Install redpanda from repository (Standard)` is executed when `https_proxy_value is not defined and (using_gcp | default(false)) is false`
`Install redpanda from repository (GCP)` is executed when `(using_gcp | default(false)) is not false`.
This can be summarised as:
|https_proxy | using_gcp| Task | 
| ----- | -----------| ----------- |
| unset (or `''`) | …
=> Implemented fix for upgrades to RPM/Debian packages not registering the `package_result` variable causing upgrades not to trigger a restart.

galaxy.yml, roles/redpanda_broker/tasks/start-redpanda.yml
The current implementation did not handle passing redpanda through the hosts file and would throw an error
```
TASK [redpanda.cluster.redpanda_broker : Merge with user-provided host specific overrides (via host_specific_override variable)] ****************************************************************
task path: /root/.ansible/collections/ansible_collections/redpanda/cluster/roles/redpanda_broker/tasks/start-redpanda.yml:63
fatal: [node-a]: FAILED! => {
"msg": "Unexpected templating type error occurred on ({{ configuration | combine((host_specific_override | default('{}') | from_json), recursive=True) }}): the JSON object must be str, bytes or bytearray, not dict. the JSON object must be str, bytes or bytearray, not dict"
}
fatal: [node-b]: FAILED! => {
"msg": "Unexpected templating …
```
=> Fix: properly handle passing redpanda variable in the hosts file

roles/redpanda_broker/tasks/install-certs.yml
These checks are improperly stopping task execution when they're trying to use the role to copy their certs without having it generate them.
=> fix: remove bad checks

galaxy.yml, roles/demo_certs/defaults/main.yml, roles/demo_certs/tasks/generate-csrs-keystore.yml, roles/demo_certs/tasks/generate-csrs.yml, roles/redpanda_broker/defaults/main.yml, roles/redpanda_broker/tasks/install-certs.yml, roles/redpanda_broker/tasks/install-nightly-build.yml, roles/redpanda_broker/tasks/main.yml, roles/redpanda_broker/tasks/safe-restart.yml, roles/redpanda_connect/defaults/main.yml, roles/redpanda_connect/tasks/install-certs.yml, roles/redpanda_console/tasks/install-certs.yml
Currently we can only build against the release candidates which is usually enough but for testing features that are still being built using tiered storage this is very helpful. 
This PR also includes a security fix and a bugfix.
=> Add nightly build support

roles/redpanda_broker/defaults/main.yml, roles/redpanda_broker/tasks/fips-assert.yml, roles/redpanda_broker/tasks/install-rp-rpm.yml, roles/redpanda_broker/templates/configs/fips.j2, roles/redpanda_broker/vars/main.yml
Second attempt at getting automated fips installs, now working with the new consolidated package deployment mechanism for supporting 24.3 releases correctly. 
There are two variables to pay attention to:
1. enable_fips = true|false (default=false). This is an ansible level variable for flipping the install process to FIPS package ordering.
2. fips_mode = disabled|permissive|enabled (default=disabled). This is a Redpanda-level configuration for configuring the broker.
If enable_fips=true and fips_mode=enabled, we also proactively check the state of the OS deployment's FIPS support. If the OS appears to be incorrectly configured for FIPS, we have an assert that bails out. This assert can be bypassed by setting fips_mode=permissive.
=> RHEL-based OS support for deploying FIPS-enabled RP clusters 

roles/system_setup/tasks/install-node-deps-rpm.yml
When installing on Amazon Linux 2023, the curl and curl-minimal packages conflict. This allows erasing of installed packages to replace curl-minimal with curl.
=> fix: allow erasing curl
